'use client';

import { Download } from 'lucide-react';
import { jsPDF } from 'jspdf';
import type { AnalysisResult } from '@/lib/types';

interface DoctorCardProps {
  result: AnalysisResult;
}

export default function DoctorCard({ result }: DoctorCardProps) {
  function generatePDF() {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('CascadeGuard — Medication Cascade Report', pageWidth / 2, y, {
      align: 'center',
    });
    y += 10;

    // Date
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, {
      align: 'center',
    });
    y += 15;

    // Medication list
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Medications Entered:', 20, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    for (const med of result.medications) {
      doc.text(`• ${med.genericName}`, 25, y);
      y += 6;
    }
    y += 5;

    // Cascades
    if (result.cascades.length > 0) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(
        `Potential Prescribing Cascades Identified (${result.cascades.length}):`,
        20,
        y
      );
      y += 10;

      for (const cascade of result.cascades) {
        // Check for page overflow
        if (y > 250) {
          doc.addPage();
          y = 20;
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.text(
          `${cascade.drugA.genericName} > ${cascade.pattern.sideEffect} > ${cascade.drugB.genericName}`,
          25,
          y
        );
        y += 6;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.text(`Severity: ${cascade.severity}`, 30, y);
        y += 5;

        if (cascade.faersCount > 0) {
          doc.text(
            `FDA adverse event reports: ${cascade.faersCount.toLocaleString()}`,
            30,
            y
          );
          y += 5;
        }

        const recText = `Recommendation: ${cascade.pattern.recommendation}`;
        const recLines = doc.splitTextToSize(recText, pageWidth - 55);
        doc.text(recLines, 30, y);
        y += recLines.length * 4 + 6;
      }
    }

    // Chains
    if (result.chains.length > 0) {
      y += 5;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Linked Chains:', 20, y);
      y += 7;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      for (const chain of result.chains) {
        doc.text(`• ${chain.description.replace(/→/g, '>')} (${chain.depth}-drug chain)`, 25, y);
        y += 6;
      }
    }

    // Footer / Disclaimer — ensure it's below content
    if (y > 255) {
      doc.addPage();
      y = 20;
    }
    const footerY = Math.max(y + 15, 275);
    doc.setDrawColor(200);
    doc.line(20, footerY - 5, pageWidth - 20, footerY - 5);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(
      'Generated by CascadeGuard (cascadeguard.sardella.dev). Based on published PIPC cascade patterns',
      pageWidth / 2,
      footerY,
      { align: 'center' }
    );
    doc.text(
      '(European Geriatric Medicine, 2025). This is not medical advice — discuss with your healthcare provider.',
      pageWidth / 2,
      footerY + 4,
      { align: 'center' }
    );

    doc.save('cascadeguard-report.pdf');
  }

  if (result.cascades.length === 0) return null;

  return (
    <div className="text-center">
      <button
        onClick={generatePDF}
        className="inline-flex items-center gap-2 px-6 py-3 bg-cascade-primary text-white font-semibold rounded-lg hover:bg-cascade-primary-hover transition-colors text-lg"
        aria-label="Download a PDF summary to bring to your doctor"
      >
        <Download size={20} />
        Download Doctor Card (PDF)
      </button>
      <p className="text-sm text-gray-500 mt-2">
        Print this and bring it to your next doctor&apos;s appointment
      </p>
    </div>
  );
}
